name: Build Drone Firmware
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platform
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Libs
        run: |
          arduino-cli lib install "MPU6050_light"
          arduino-cli lib install "Dabble"

      - name: Compile
        run: |
          # လက်ရှိ ဖိုင်တည်ရှိပုံအရ drone/ ကို ဖြုတ်ပြီး ပြင်ထားပါတယ်
          arduino-cli compile --fqbn esp32:esp32:esp32c3 --output-dir ./build ./drone_code.ino

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Drone-Bin-File
          path: ./build/*.bin
          
